// Generated by gencpp from file practica1/Obstaculo.msg
// DO NOT EDIT!


#ifndef PRACTICA1_MESSAGE_OBSTACULO_H
#define PRACTICA1_MESSAGE_OBSTACULO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace practica1
{
template <class ContainerAllocator>
struct Obstaculo_
{
  typedef Obstaculo_<ContainerAllocator> Type;

  Obstaculo_()
    : pose_caja()
    , name()
    , tamaño()  {
    }
  Obstaculo_(const ContainerAllocator& _alloc)
    : pose_caja(_alloc)
    , name(_alloc)
    , tamaño(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_caja_type;
  _pose_caja_type pose_caja;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tamaño_type;
  _tamaño_type tamaño;





  typedef boost::shared_ptr< ::practica1::Obstaculo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::practica1::Obstaculo_<ContainerAllocator> const> ConstPtr;

}; // struct Obstaculo_

typedef ::practica1::Obstaculo_<std::allocator<void> > Obstaculo;

typedef boost::shared_ptr< ::practica1::Obstaculo > ObstaculoPtr;
typedef boost::shared_ptr< ::practica1::Obstaculo const> ObstaculoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::practica1::Obstaculo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::practica1::Obstaculo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::practica1::Obstaculo_<ContainerAllocator1> & lhs, const ::practica1::Obstaculo_<ContainerAllocator2> & rhs)
{
  return lhs.pose_caja == rhs.pose_caja &&
    lhs.name == rhs.name &&
    lhs.tamaño == rhs.tamaño;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::practica1::Obstaculo_<ContainerAllocator1> & lhs, const ::practica1::Obstaculo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace practica1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::practica1::Obstaculo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practica1::Obstaculo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica1::Obstaculo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica1::Obstaculo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica1::Obstaculo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica1::Obstaculo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::practica1::Obstaculo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f18e27135568d04082f7d3b8323e1a5b";
  }

  static const char* value(const ::practica1::Obstaculo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf18e27135568d040ULL;
  static const uint64_t static_value2 = 0x82f7d3b8323e1a5bULL;
};

template<class ContainerAllocator>
struct DataType< ::practica1::Obstaculo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "practica1/Obstaculo";
  }

  static const char* value(const ::practica1::Obstaculo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::practica1::Obstaculo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose_caja\n"
"string name\n"
"float32[] tamaño\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::practica1::Obstaculo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::practica1::Obstaculo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_caja);
      stream.next(m.name);
      stream.next(m.tamaño);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstaculo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::practica1::Obstaculo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::practica1::Obstaculo_<ContainerAllocator>& v)
  {
    s << indent << "pose_caja: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_caja);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "tamaño[]" << std::endl;
    for (size_t i = 0; i < v.tamaño.size(); ++i)
    {
      s << indent << "  tamaño[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tamaño[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRACTICA1_MESSAGE_OBSTACULO_H
